Changelogs for Cloud Manager v1.16.0 and JS SDK v0.31.0
linode/developers pull request #248
Opened 2020-08-13 18:04 UTC by WilkinsKa1

2020-08-13 18:10 UTC, Jskobos requested changes

2020-08-13 18:10 UTC, Jskobos commented on src/content/changelog/js-client-changelog-0-31-0.md
> +version: 0.31.0-alpha.0
Version is incorrect (shouldn't be alpha)

2020-08-13 18:10 UTC, Jskobos commented on src/content/changelog/js-client-changelog-0-31-0.md
> +title: Linode APIv4 JS Client v0.31.0 (alpha)
No alpha

2020-08-13 21:06 UTC, Jskobos approved these changes

2020-08-14 19:50 UTC, WilkinsKa1 commented
Adding do not merge until latest version (1.16.2) has been pushed to production.

2020-08-18 20:36 UTC, merged