Switch locations for API specs
linode/developers pull request #43
Opened 2019-08-22 17:03 UTC by alioso

In order to release we need to switch the curling and location of the specs file

2019-08-23 19:51 UTC, Jskobos requested changes

2019-08-23 19:51 UTC, Jskobos commented on search/buildIndex.js
> +const spec = require("../static/src/api/docs/v4/spec.json");
Shouldn't be a `src` in this path

2019-08-26 12:33 UTC, alioso commented on search/buildIndex.js
> +const spec = require("../static/src/api/docs/v4/spec.json");
@Jskobos fixed

2019-08-26 13:47 UTC, Jskobos approved these changes

2019-08-26 16:19 UTC, merged