Add LKE v1.27.0 changelog
linode/developers pull request #458
Opened 2021-09-17 20:27 UTC by git-it127

2021-09-17 20:44 UTC, Charliekenney23 approved these changes

2021-09-20 12:41 UTC, g1bl3t requested changes

2021-09-20 12:41 UTC, g1bl3t commented on src/content/changelog/lke-1-27-0.md
> +* Added support for Kubernetes patch versions v1.19.15, v1.20.11, and v1.21.5.
```suggestion
* Upgraded cluster control plane components to latest available patch version: v1.19.15, v1.20.11, and v1.21.5
```

2021-09-20 12:41 UTC, g1bl3t commented on src/content/changelog/lke-1-27-0.md
> +* Upgraded Linode CCM to v0.3.15 on all LKE versions.
```suggestion
* Upgraded Linode CCM to v0.3.15 on all LKE clusters
```

2021-09-20 13:42 UTC, g1bl3t approved these changes

2021-09-20 15:58 UTC, merged